# Generated by Django 3.0.7 on 2020-06-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterMarker', '0002_image_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
