# Generated by Django 3.0.7 on 2020-06-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterMarker', '0004_auto_20200623_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='logo',
            field=models.ImageField(upload_to='images/Uploads'),
        ),
    ]
