# Generated by Django 3.0.7 on 2020-06-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdata',
            old_name='img',
            new_name='image',
        ),
    ]
