# Generated by Django 3.0.7 on 2020-06-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0002_auto_20200619_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='image',
        ),
    ]
