# Generated by Django 3.0.7 on 2020-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0003_remove_postdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='hashTags',
            field=models.TextField(blank=True),
        ),
    ]
