# Generated by Django 3.0.7 on 2020-06-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharesite', '0004_postdata_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
